services:
  api:
    build: .
    image: inquest-api
    container_name: api
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - qdrant
    env_file:
      - .env
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AZURE_SPEECH_KEY=${AZURE_SPEECH_KEY}
      - AZURE_SPEECH_REGION=${AZURE_SPEECH_REGION}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334" # grpc
    volumes:
      - ./qdrant_data:/qdrant/storage

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
